USE [POSUTSimplex]
GO

/****** Object:  StoredProcedure [dbo].[VENTAS_ARTICULOS_HISTORICO]    Script Date: 17/11/2024 16:57:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[VENTAS_ARTICULOS_HISTORICO]
(@LETRAS_CODIGO VARCHAR(2), @FECHA_DESDE VARCHAR(8), @FECHA_HASTA VARCHAR(8))
AS
BEGIN

SELECT 
CAST(YEAR(V.fechaHora) AS VARCHAR) AS ANIO,
CAST(MONTH(V.fechaHora) AS VARCHAR) AS MES,
F.DESCRIPCION AS FAMILIA, 
SUM(VA.precio) AS VENTA_TOTAL,
SUM(VA.CANTIDAD) AS CANTIDAD_TOTAL

 FROM Ventas_Articulos VA
INNER JOIN Ventas V ON V.numVenta=VA.CFVenNumVenta
INNER JOIN Articulos A ON A.codigo = va.CFArtCodigo
INNER JOIN FAMILIA F ON A.Familia=F.ID
WHERE codigo LIKE @LETRAS_CODIGO+'%'
AND CAST(V.fechaHora AS DATE) BETWEEN @FECHA_DESDE AND @FECHA_HASTA
GROUP BY ROLLUP(CAST(YEAR(V.fechaHora) AS VARCHAR),CAST(MONTH(V.fechaHora) AS VARCHAR),F.DESCRIPCION)
ORDER BY 1 DESC, 2 DESC, 3 DESC
END
GO

