
/****** Object:  Table [dbo].[MEDIO_PAGO]    Script Date: 16/06/2023 15:02:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MEDIO_PAGO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](50) NOT NULL,
	[ACTIVO] [bit] NULL,
	[ESDEFAULT] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MEDIO_PAGO] ADD  DEFAULT ((0)) FOR [ESDEFAULT]
GO

INSERT INTO MEDIO_PAGO (DESCRIPCION,ACTIVO,ESDEFAULT)
VALUES('EFECTIVO',1,1)
INSERT INTO MEDIO_PAGO (DESCRIPCION,ACTIVO,ESDEFAULT)
VALUES('DEBITO',1,0)
INSERT INTO MEDIO_PAGO (DESCRIPCION,ACTIVO,ESDEFAULT)
VALUES('CREDITO',1,0)
INSERT INTO MEDIO_PAGO (DESCRIPCION,ACTIVO,ESDEFAULT)
VALUES('MERCADO PAGO',1,0)
INSERT INTO MEDIO_PAGO (DESCRIPCION,ACTIVO,ESDEFAULT)
VALUES('BILLETERA SFE',1,0)
INSERT INTO MEDIO_PAGO (DESCRIPCION,ACTIVO,ESDEFAULT)
VALUES('TRANSFERENCIA',1,0)