USE [POSUTSimplex]
GO

/****** Object:  Table [dbo].[FE]    Script Date: 07/06/2023 16:02:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FacturaElectronica](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[VENTA_ID] [bigint] NOT NULL,
	[REQUEST] [varchar](max) NULL,
	[REQUEST_DETALLE] [varchar](max) NULL,
	[RESPONSE] [varchar](max) NULL,
	[OBSERVACIONES] [varchar](max) NULL,
	[RESULTADO] [varchar](5) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


